#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotakDocuMentor.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KotakEmployee")]
	public partial class KotakEmployeeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public KotakEmployeeDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["KotakEmployeeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KotakEmployeeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotakEmployeeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotakEmployeeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotakEmployeeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInfo")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _UserLoginName;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Segment;
		
		private string _Division;
		
		private string _Function;
		
		private string _Role;
		
		private string _CC;
		
		private string _SupervisorID;
		
		private string _Email;
		
		private string _EmpId;
		
		private string _Business_TrainerId;
		
		private string _HR_TrainerId;
		
		private string _Zonal_level_TrainerId;
		
		private string _Regional_level_TrainerId;
		
		private string _Area_level_TrainerId;
		
		private string _Branch_TrainerId;
		
		private System.Nullable<decimal> _PERSON_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnUserLoginNameChanging(string value);
    partial void OnUserLoginNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnSegmentChanging(string value);
    partial void OnSegmentChanged();
    partial void OnDivisionChanging(string value);
    partial void OnDivisionChanged();
    partial void OnFunctionChanging(string value);
    partial void OnFunctionChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnCCChanging(string value);
    partial void OnCCChanged();
    partial void OnSupervisorIDChanging(string value);
    partial void OnSupervisorIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEmpIdChanging(string value);
    partial void OnEmpIdChanged();
    partial void OnBusiness_TrainerIdChanging(string value);
    partial void OnBusiness_TrainerIdChanged();
    partial void OnHR_TrainerIdChanging(string value);
    partial void OnHR_TrainerIdChanged();
    partial void OnZonal_level_TrainerIdChanging(string value);
    partial void OnZonal_level_TrainerIdChanged();
    partial void OnRegional_level_TrainerIdChanging(string value);
    partial void OnRegional_level_TrainerIdChanged();
    partial void OnArea_level_TrainerIdChanging(string value);
    partial void OnArea_level_TrainerIdChanged();
    partial void OnBranch_TrainerIdChanging(string value);
    partial void OnBranch_TrainerIdChanged();
    partial void OnPERSON_IDChanging(System.Nullable<decimal> value);
    partial void OnPERSON_IDChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginName", DbType="NVarChar(80)")]
		public string UserLoginName
		{
			get
			{
				return this._UserLoginName;
			}
			set
			{
				if ((this._UserLoginName != value))
				{
					this.OnUserLoginNameChanging(value);
					this.SendPropertyChanging();
					this._UserLoginName = value;
					this.SendPropertyChanged("UserLoginName");
					this.OnUserLoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(70)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(70)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment", DbType="NVarChar(100)")]
		public string Segment
		{
			get
			{
				return this._Segment;
			}
			set
			{
				if ((this._Segment != value))
				{
					this.OnSegmentChanging(value);
					this.SendPropertyChanging();
					this._Segment = value;
					this.SendPropertyChanged("Segment");
					this.OnSegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NVarChar(100)")]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Function]", Storage="_Function", DbType="NVarChar(100)")]
		public string Function
		{
			get
			{
				return this._Function;
			}
			set
			{
				if ((this._Function != value))
				{
					this.OnFunctionChanging(value);
					this.SendPropertyChanging();
					this._Function = value;
					this.SendPropertyChanged("Function");
					this.OnFunctionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(100)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC", DbType="NVarChar(100)")]
		public string CC
		{
			get
			{
				return this._CC;
			}
			set
			{
				if ((this._CC != value))
				{
					this.OnCCChanging(value);
					this.SendPropertyChanging();
					this._CC = value;
					this.SendPropertyChanged("CC");
					this.OnCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisorID", DbType="NVarChar(100)")]
		public string SupervisorID
		{
			get
			{
				return this._SupervisorID;
			}
			set
			{
				if ((this._SupervisorID != value))
				{
					this.OnSupervisorIDChanging(value);
					this.SendPropertyChanging();
					this._SupervisorID = value;
					this.SendPropertyChanged("SupervisorID");
					this.OnSupervisorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpId", DbType="NVarChar(100)")]
		public string EmpId
		{
			get
			{
				return this._EmpId;
			}
			set
			{
				if ((this._EmpId != value))
				{
					this.OnEmpIdChanging(value);
					this.SendPropertyChanging();
					this._EmpId = value;
					this.SendPropertyChanged("EmpId");
					this.OnEmpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_TrainerId", DbType="NVarChar(50)")]
		public string Business_TrainerId
		{
			get
			{
				return this._Business_TrainerId;
			}
			set
			{
				if ((this._Business_TrainerId != value))
				{
					this.OnBusiness_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Business_TrainerId = value;
					this.SendPropertyChanged("Business_TrainerId");
					this.OnBusiness_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR_TrainerId", DbType="NVarChar(50)")]
		public string HR_TrainerId
		{
			get
			{
				return this._HR_TrainerId;
			}
			set
			{
				if ((this._HR_TrainerId != value))
				{
					this.OnHR_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._HR_TrainerId = value;
					this.SendPropertyChanged("HR_TrainerId");
					this.OnHR_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zonal_level_TrainerId", DbType="NVarChar(50)")]
		public string Zonal_level_TrainerId
		{
			get
			{
				return this._Zonal_level_TrainerId;
			}
			set
			{
				if ((this._Zonal_level_TrainerId != value))
				{
					this.OnZonal_level_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Zonal_level_TrainerId = value;
					this.SendPropertyChanged("Zonal_level_TrainerId");
					this.OnZonal_level_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Regional_level_TrainerId", DbType="NVarChar(50)")]
		public string Regional_level_TrainerId
		{
			get
			{
				return this._Regional_level_TrainerId;
			}
			set
			{
				if ((this._Regional_level_TrainerId != value))
				{
					this.OnRegional_level_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Regional_level_TrainerId = value;
					this.SendPropertyChanged("Regional_level_TrainerId");
					this.OnRegional_level_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area_level_TrainerId", DbType="NVarChar(50)")]
		public string Area_level_TrainerId
		{
			get
			{
				return this._Area_level_TrainerId;
			}
			set
			{
				if ((this._Area_level_TrainerId != value))
				{
					this.OnArea_level_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Area_level_TrainerId = value;
					this.SendPropertyChanged("Area_level_TrainerId");
					this.OnArea_level_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_TrainerId", DbType="NVarChar(50)")]
		public string Branch_TrainerId
		{
			get
			{
				return this._Branch_TrainerId;
			}
			set
			{
				if ((this._Branch_TrainerId != value))
				{
					this.OnBranch_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Branch_TrainerId = value;
					this.SendPropertyChanged("Branch_TrainerId");
					this.OnBranch_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSON_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PERSON_ID
		{
			get
			{
				return this._PERSON_ID;
			}
			set
			{
				if ((this._PERSON_ID != value))
				{
					this.OnPERSON_IDChanging(value);
					this.SendPropertyChanging();
					this._PERSON_ID = value;
					this.SendPropertyChanged("PERSON_ID");
					this.OnPERSON_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
