#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotakDocuMentor.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ELEARNING")]
	public partial class KotakEmployeeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public KotakEmployeeDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ELEARNINGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KotakEmployeeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotakEmployeeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotakEmployeeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KotakEmployeeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInfo")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _UserLoginName;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.Nullable<int> _CustomerId;
		
		private bool _isDelete;
		
		private string _CreatedBy;
		
		private System.DateTime _CreatedOn;
		
		private string _ModifiedBy;
		
		private System.DateTime _ModifiedOn;
		
		private System.Nullable<int> _EditLockNumber;
		
		private System.Nullable<bool> _isActive;
		
		private string _Segment;
		
		private string _Division;
		
		private string _Function;
		
		private string _Role;
		
		private string _LOC;
		
		private string _LOB;
		
		private string _CC;
		
		private string _SupervisorID;
		
		private System.Nullable<System.DateTime> _DOJ;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _Email;
		
		private string _EmpId;
		
		private System.Nullable<System.DateTime> _DeActiveDate;
		
		private string _Business_TrainerId;
		
		private string _HR_TrainerId;
		
		private string _LOC_Code;
		
		private string _Zonal_level_TrainerId;
		
		private string _Regional_level_TrainerId;
		
		private string _Area_level_TrainerId;
		
		private string _Branch_TrainerId;
		
		private System.Nullable<System.DateTime> _EMP_VERDATE;
		
		private System.Nullable<decimal> _PERSON_ID;
		
		private System.Nullable<System.DateTime> _LAST_WORKING_DATE;
		
		private int _UnqId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnUserLoginNameChanging(string value);
    partial void OnUserLoginNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnCustomerIdChanging(System.Nullable<int> value);
    partial void OnCustomerIdChanged();
    partial void OnisDeleteChanging(bool value);
    partial void OnisDeleteChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnModifiedOnChanging(System.DateTime value);
    partial void OnModifiedOnChanged();
    partial void OnEditLockNumberChanging(System.Nullable<int> value);
    partial void OnEditLockNumberChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    partial void OnSegmentChanging(string value);
    partial void OnSegmentChanged();
    partial void OnDivisionChanging(string value);
    partial void OnDivisionChanged();
    partial void OnFunctionChanging(string value);
    partial void OnFunctionChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnLOCChanging(string value);
    partial void OnLOCChanged();
    partial void OnLOBChanging(string value);
    partial void OnLOBChanged();
    partial void OnCCChanging(string value);
    partial void OnCCChanged();
    partial void OnSupervisorIDChanging(string value);
    partial void OnSupervisorIDChanged();
    partial void OnDOJChanging(System.Nullable<System.DateTime> value);
    partial void OnDOJChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnEmpIdChanging(string value);
    partial void OnEmpIdChanged();
    partial void OnDeActiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeActiveDateChanged();
    partial void OnBusiness_TrainerIdChanging(string value);
    partial void OnBusiness_TrainerIdChanged();
    partial void OnHR_TrainerIdChanging(string value);
    partial void OnHR_TrainerIdChanged();
    partial void OnLOC_CodeChanging(string value);
    partial void OnLOC_CodeChanged();
    partial void OnZonal_level_TrainerIdChanging(string value);
    partial void OnZonal_level_TrainerIdChanged();
    partial void OnRegional_level_TrainerIdChanging(string value);
    partial void OnRegional_level_TrainerIdChanged();
    partial void OnArea_level_TrainerIdChanging(string value);
    partial void OnArea_level_TrainerIdChanged();
    partial void OnBranch_TrainerIdChanging(string value);
    partial void OnBranch_TrainerIdChanged();
    partial void OnEMP_VERDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_VERDATEChanged();
    partial void OnPERSON_IDChanging(System.Nullable<decimal> value);
    partial void OnPERSON_IDChanged();
    partial void OnLAST_WORKING_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_WORKING_DATEChanged();
    partial void OnUnqIdChanging(int value);
    partial void OnUnqIdChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginName", DbType="NVarChar(80)")]
		public string UserLoginName
		{
			get
			{
				return this._UserLoginName;
			}
			set
			{
				if ((this._UserLoginName != value))
				{
					this.OnUserLoginNameChanging(value);
					this.SendPropertyChanging();
					this._UserLoginName = value;
					this.SendPropertyChanged("UserLoginName");
					this.OnUserLoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(70)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(70)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int")]
		public System.Nullable<int> CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="Bit NOT NULL")]
		public bool isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this.OnisDeleteChanging(value);
					this.SendPropertyChanging();
					this._isDelete = value;
					this.SendPropertyChanged("isDelete");
					this.OnisDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(80)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(80)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditLockNumber", DbType="Int")]
		public System.Nullable<int> EditLockNumber
		{
			get
			{
				return this._EditLockNumber;
			}
			set
			{
				if ((this._EditLockNumber != value))
				{
					this.OnEditLockNumberChanging(value);
					this.SendPropertyChanging();
					this._EditLockNumber = value;
					this.SendPropertyChanged("EditLockNumber");
					this.OnEditLockNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment", DbType="NVarChar(100)")]
		public string Segment
		{
			get
			{
				return this._Segment;
			}
			set
			{
				if ((this._Segment != value))
				{
					this.OnSegmentChanging(value);
					this.SendPropertyChanging();
					this._Segment = value;
					this.SendPropertyChanged("Segment");
					this.OnSegmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NVarChar(100)")]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Function]", Storage="_Function", DbType="NVarChar(100)")]
		public string Function
		{
			get
			{
				return this._Function;
			}
			set
			{
				if ((this._Function != value))
				{
					this.OnFunctionChanging(value);
					this.SendPropertyChanging();
					this._Function = value;
					this.SendPropertyChanged("Function");
					this.OnFunctionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(100)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOC", DbType="NVarChar(100)")]
		public string LOC
		{
			get
			{
				return this._LOC;
			}
			set
			{
				if ((this._LOC != value))
				{
					this.OnLOCChanging(value);
					this.SendPropertyChanging();
					this._LOC = value;
					this.SendPropertyChanged("LOC");
					this.OnLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOB", DbType="NVarChar(100)")]
		public string LOB
		{
			get
			{
				return this._LOB;
			}
			set
			{
				if ((this._LOB != value))
				{
					this.OnLOBChanging(value);
					this.SendPropertyChanging();
					this._LOB = value;
					this.SendPropertyChanged("LOB");
					this.OnLOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC", DbType="NVarChar(100)")]
		public string CC
		{
			get
			{
				return this._CC;
			}
			set
			{
				if ((this._CC != value))
				{
					this.OnCCChanging(value);
					this.SendPropertyChanging();
					this._CC = value;
					this.SendPropertyChanged("CC");
					this.OnCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisorID", DbType="NVarChar(100)")]
		public string SupervisorID
		{
			get
			{
				return this._SupervisorID;
			}
			set
			{
				if ((this._SupervisorID != value))
				{
					this.OnSupervisorIDChanging(value);
					this.SendPropertyChanging();
					this._SupervisorID = value;
					this.SendPropertyChanged("SupervisorID");
					this.OnSupervisorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOJ", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOJ
		{
			get
			{
				return this._DOJ;
			}
			set
			{
				if ((this._DOJ != value))
				{
					this.OnDOJChanging(value);
					this.SendPropertyChanging();
					this._DOJ = value;
					this.SendPropertyChanged("DOJ");
					this.OnDOJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpId", DbType="NVarChar(100)")]
		public string EmpId
		{
			get
			{
				return this._EmpId;
			}
			set
			{
				if ((this._EmpId != value))
				{
					this.OnEmpIdChanging(value);
					this.SendPropertyChanging();
					this._EmpId = value;
					this.SendPropertyChanged("EmpId");
					this.OnEmpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeActiveDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DeActiveDate
		{
			get
			{
				return this._DeActiveDate;
			}
			set
			{
				if ((this._DeActiveDate != value))
				{
					this.OnDeActiveDateChanging(value);
					this.SendPropertyChanging();
					this._DeActiveDate = value;
					this.SendPropertyChanged("DeActiveDate");
					this.OnDeActiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_TrainerId", DbType="NVarChar(50)")]
		public string Business_TrainerId
		{
			get
			{
				return this._Business_TrainerId;
			}
			set
			{
				if ((this._Business_TrainerId != value))
				{
					this.OnBusiness_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Business_TrainerId = value;
					this.SendPropertyChanged("Business_TrainerId");
					this.OnBusiness_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR_TrainerId", DbType="NVarChar(50)")]
		public string HR_TrainerId
		{
			get
			{
				return this._HR_TrainerId;
			}
			set
			{
				if ((this._HR_TrainerId != value))
				{
					this.OnHR_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._HR_TrainerId = value;
					this.SendPropertyChanged("HR_TrainerId");
					this.OnHR_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOC_Code", DbType="NVarChar(100)")]
		public string LOC_Code
		{
			get
			{
				return this._LOC_Code;
			}
			set
			{
				if ((this._LOC_Code != value))
				{
					this.OnLOC_CodeChanging(value);
					this.SendPropertyChanging();
					this._LOC_Code = value;
					this.SendPropertyChanged("LOC_Code");
					this.OnLOC_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zonal_level_TrainerId", DbType="NVarChar(50)")]
		public string Zonal_level_TrainerId
		{
			get
			{
				return this._Zonal_level_TrainerId;
			}
			set
			{
				if ((this._Zonal_level_TrainerId != value))
				{
					this.OnZonal_level_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Zonal_level_TrainerId = value;
					this.SendPropertyChanged("Zonal_level_TrainerId");
					this.OnZonal_level_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Regional_level_TrainerId", DbType="NVarChar(50)")]
		public string Regional_level_TrainerId
		{
			get
			{
				return this._Regional_level_TrainerId;
			}
			set
			{
				if ((this._Regional_level_TrainerId != value))
				{
					this.OnRegional_level_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Regional_level_TrainerId = value;
					this.SendPropertyChanged("Regional_level_TrainerId");
					this.OnRegional_level_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area_level_TrainerId", DbType="NVarChar(50)")]
		public string Area_level_TrainerId
		{
			get
			{
				return this._Area_level_TrainerId;
			}
			set
			{
				if ((this._Area_level_TrainerId != value))
				{
					this.OnArea_level_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Area_level_TrainerId = value;
					this.SendPropertyChanged("Area_level_TrainerId");
					this.OnArea_level_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_TrainerId", DbType="NVarChar(50)")]
		public string Branch_TrainerId
		{
			get
			{
				return this._Branch_TrainerId;
			}
			set
			{
				if ((this._Branch_TrainerId != value))
				{
					this.OnBranch_TrainerIdChanging(value);
					this.SendPropertyChanging();
					this._Branch_TrainerId = value;
					this.SendPropertyChanged("Branch_TrainerId");
					this.OnBranch_TrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_VERDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EMP_VERDATE
		{
			get
			{
				return this._EMP_VERDATE;
			}
			set
			{
				if ((this._EMP_VERDATE != value))
				{
					this.OnEMP_VERDATEChanging(value);
					this.SendPropertyChanging();
					this._EMP_VERDATE = value;
					this.SendPropertyChanged("EMP_VERDATE");
					this.OnEMP_VERDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSON_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PERSON_ID
		{
			get
			{
				return this._PERSON_ID;
			}
			set
			{
				if ((this._PERSON_ID != value))
				{
					this.OnPERSON_IDChanging(value);
					this.SendPropertyChanging();
					this._PERSON_ID = value;
					this.SendPropertyChanged("PERSON_ID");
					this.OnPERSON_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_WORKING_DATE", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LAST_WORKING_DATE
		{
			get
			{
				return this._LAST_WORKING_DATE;
			}
			set
			{
				if ((this._LAST_WORKING_DATE != value))
				{
					this.OnLAST_WORKING_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_WORKING_DATE = value;
					this.SendPropertyChanged("LAST_WORKING_DATE");
					this.OnLAST_WORKING_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnqId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int UnqId
		{
			get
			{
				return this._UnqId;
			}
			set
			{
				if ((this._UnqId != value))
				{
					this.OnUnqIdChanging(value);
					this.SendPropertyChanging();
					this._UnqId = value;
					this.SendPropertyChanged("UnqId");
					this.OnUnqIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
