<?xml version="1.0" encoding="utf-8"?><Database Name="DocuMentorDB" Class="TheCoachDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=IPC;Initial Catalog=DocuMentorDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DocuMentorDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sections" Member="Sections">
    <Type Name="Section">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="module_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="html_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="module_Section" Member="Module" ThisKey="module_id" OtherKey="id" Type="Module" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.modules" Member="Modules">
    <Type Name="Module">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="body_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="script_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="module_Section" Member="Sections" ThisKey="id" OtherKey="module_id" Type="Section" />
    </Type>
  </Table>
</Database>